name: Test Projects

on:
  push:
  pull_request:

jobs:
  build:
    name: 'Test (${{ matrix.project.test }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - test: Mimir.Worker.Tests
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet test ${{ matrix.project.test }}
